name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Laravel-React image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/laravel-react-app:latest -f Dockerfile .
        docker push ${{ secrets.DOCKER_USERNAME }}/laravel-react-app:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.18.0'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/laravel-react-deployment.yaml
