export const primeIcons = [
   { name: "fa-brands fa-telegram", className: "fa-brands fa-telegram" },
   { name: "fa-brands fa-discord", className: "fa-brands fa-discord" },
   { name: "fa-brands fa-tiktok", className: "fa-brands fa-tiktok" },
   { name: "fa-brands fa-facebook", className: "fa-brands fa-facebook" },
   { name: "fa-brands fa-x-twitter", className: "fa-brands fa-x-twitter" },
   { name: "fa-brands fa-instagram", className: "fa-brands fa-instagram" },
   { name: "fa-brands fa-youtube", className: "fa-brands fa-youtube" },
   { name: "fa-brands fa-linkedin", className: "fa-brands fa-linkedin" },
   { name: "fa-brands fa-snapchat", className: "fa-brands fa-snapchat" },
   { name: "fa-brands fa-reddit", className: "fa-brands fa-reddit" },
   { name: "fa-brands fa-pinterest", className: "fa-brands fa-pinterest" },
   { name: "fa-brands fa-whatsapp", className: "fa-brands fa-whatsapp" },
   { name: "fa-brands fa-tumblr", className: "fa-brands fa-tumblr" },
   { name: "fa-brands fa-vk", className: "fa-brands fa-vk" },
   { name: "fa-brands fa-wechat", className: "fa-brands fa-wechat" },
   { name: "fa-brands fa-line", className: "fa-brands fa-line" },
   { name: "fa-solid fa-ellipsis", className: "fa-solid fa-ellipsis" },
];
